packages/app-store/googlecalendar/lib/CalendarService.ts
Trying to optimize for performance again and was looking into batch requesting all user availabilities. It seems that the google calendar API NodeJs client doesn't have support for batch requesting. But [this comment](https://github.com/googleapis/google-api-nodejs-client/issues/2375#issuecomment-717470917) basically recommends to use http2. Cannot hurt I think.
=> Use http2 for Google Calendar API

packages/app-store/googlecalendar/lib/CalendarService.ts, packages/core/getBusyTimes.ts, packages/lib/logger.ts, packages/trpc/server/routers/viewer/slots.tsx
When getting the slots for the calendar widget half of the time is spent just creating the scaffold based on all team members working hours. With ~20 team members this alone can take around 2 seconds of CPU bound work. Since we basically do not want to use Calcom's working hours anyway we can safely remove this part and gain performance.
I also removed some excessive logging and configured the logger to log as JSON in production environment.
=> Performance improvement of main schedule endpoint

apps/web/components/booking/pages/BookingPage.tsx, apps/web/components/v2/eventtype/CustomInputTypeForm.tsx, apps/web/public/static/locales/de/common.json, apps/web/public/static/locales/en/common.json, packages/prisma/migrations/20221103115800_add_hidden_custom_input_type/migration.sql, packages/prisma/schema.prisma
A hidden custom input makes sense when you want to attach some data to a booking. But you don't want the user to see or be able to edit that data.
=> Add hidden custom input type

packages/lib/logger.ts, packages/trpc/server/routers/viewer/slots.tsx
This greatly improves the performance by limiting the time slots that have to be checked. The calendar widget usually sends a start time that equals the beginning of the month and an end time that equals the end of the month.
- But the start time can be immediately cut to the current time. You can never book a slot that is before now anyway.
- In the case where a booking can only be scheduled until a certain amount of days into the future, the end time can be cut, too.
Example: Today is Nov 9 and the event type is setup to only allow bookings up until 7 days from now. Now instead of having to calculate the slots from Nov 1 until Nov 30, we can immediately limit the range to Nov 9 + 7 days. This is calculating 8 days vs. 30 days.
So instead of calculating all slots first and only then …
=> Performance improvement when calculating slots

apps/web/components/booking/pages/BookingPage.tsx, apps/web/pages/success.tsx
The recent upstream release introduced a bug that causes the successful booking to be confirmed with an `undefined` duration. Not only fixes this the undefined duration. But it also moves the firing of the event to a different place. The event should only fire once and only once the appointment is booked, not when the success page is accessed (in a `useEffect` hook).
https://github.com/calcom/cal.com/pull/5660/files#diff-1e9afd5de724161cc0bf80b40ac965e2e18355f836926f06460bd2d992bf1f9cR235
=> Fix calculated duration undefined

packages/core/EventManager.ts, packages/features/bookings/lib/handleNewBooking.ts
Calcom's rescheduling assumes that the new appointment is with the same user the original appointment was done with. But when the user actually changes it blows up. In that case you cannot simply update the Google calendar event. It has to be deleted in the original Google calendar and a new one has to be created in the new Google calendar.
I don't even want to open a PR in the original repo. The fact that this is running live in production and nobody seems to notice or care is just mind boggling. I cannot believe that we are the first to notice this.
=> Bugfix: Ability to reschedule with different user

packages/trpc/server/routers/viewer/slots.tsx
Fixes a bug where the calendar does not show all available slots when selecting a custom event duration.
Use the `input.duration` when checking if a user is available for a particular slot.
https://tourlane.atlassian.net/browse/TRIP-7209
=> Fix multiple durations issue

apps/web/components/booking/pages/AvailabilityPage.tsx, packages/trpc/server/routers/viewer/slots.tsx
If the availability endpoint is called with `rescheduleWithSameUser: true` and if there is a booking found using `rescheduleUid` the endpoint now only returns availabilities for the same user. That means the user of the original booking will be the user of the new rescheduled booking, too.
=> Reschedule with same user

apps/web/test/lib/slots.test.ts, packages/dayjs/index.ts, packages/lib/logger.ts, packages/lib/slots.ts, packages/trpc/server/routers/viewer/slots.tsx
When there is only one host (only one calendar to check for conflicts) we now generate more compact slots and try to minimize empty gaps between blockers and slots. Calcom usually generates all slots first and only then discards all slots that are not available due to blockers in the calendar. For example if the event length is 30 minutes and the host has some blocker until 10:15 then the next possible slot would be 10:30 to 11:00. The time from 10:15 until 10:30 is wasted. With this approach the next slot will start directly after the blocker at 10:15 leading to a more efficient usage of free time.
We only apply the compact slot generation in single host situations. In situations with more hosts (team events) this approach is less desirable and would be more complex to implement.
=> Compact slots for single host events

packages/core/getBusyTimes.ts, packages/lib/slots.ts, packages/trpc/server/routers/viewer/slots.tsx
Make `getBufferedBusyTimes` actually return Dayjs instances and not datetime strings. Those values are needed a lot down the line for calculating availability. So returning Dayjs instances removes the need to parse them again and again.
With team events that have many users this code path is executed thousands of time: number of slots * number of busy times actually. This simple change saves up to a second of raw CPU time with a realistic event that has around 20 users.
=> Refactor and performance improvement of availability check

packages/trpc/server/routers/viewer/slots.tsx
Fixes a bug where the busy times are not correctly grouped by day. Busy times in a calendar can span multiple days. In this case the busy time must be added to all days it covers.
Ex. start: 2023-01-01Z20:00:00Z end: 2023-02-01Z10:00:00Z
covers two days and thus if you group this by day you have to add it to both 2023-01-01 and 2023-01-02. Otherwise later down in the code path it is assumed that there are no blockers on 2023-01-02.
=> Bugfix: Busy times grouping

apps/web/components/booking/pages/AvailabilityPage.tsx, packages/trpc/server/routers/viewer/slots.tsx
Booking limits (earliest start time and latest bookable day) can now be configured dynamically via query params.
=> Booking limits via query params

apps/web/test/lib/slots.test.ts, packages/core/getBusyTimes.ts, packages/lib/slots.ts, packages/trpc/server/routers/viewer/slots.tsx
**Three improvements to improve performance of the availability endpoint**
One database database query for scheduled bookings instead of one query for each user.
Micro improvement of `checkIfIsAvailable` by using `some` instead of `every`
The third improvemen actually really makes the difference. Before the busy times were stored in an array of arrays, one element for each user. So for checking if a user is available for a particular slot we had to do two array operations: `find` and `some`. First `find` the user's busy times and then compare the slot against the busy slots (`some`).
```typescript
allBusyTimes.find(e => e.userId === user.id).some(busy => slotsOverlap(slot, busy))
```
This becomes very slow the more slots there are and the more users there are.
Now we have a more efficient …
=> Improve availability endpoint performance

apps/web/package.json, apps/web/pages/bookings/[status].tsx, packages/features/bookings/components/PeopleFilter.tsx, packages/ui/components/popover/AnimatedPopover.tsx, yarn.lock
- Fix load more issue
- Add Scrollable area to People Filter
=> [fix] Loadmore bookings and Scrollable Area in People Filter

packages/app-store/googlecalendar/lib/CalendarService.ts
https://tourlane.atlassian.net/browse/TRIP-10326
=> [feat][TRIP-10326] Add sentry captureMessage to Google calendar services

apps/web/components/booking/pages/AvailabilityPage.tsx, apps/web/components/booking/pages/BookingPage.tsx
Our customers should not be able to use Calcom directly. We therefore disable the booking pages for them.
https://tourlane.atlassian.net/browse/TRIP-10691
=> [fix] Disable booking pages when not embedded

packages/prisma/migrations/20231111144534_add_unique_index_on_booking_user_id_and_start_time/migration.sql
When booking requests come in at the same time there is a race condition where multiple bookings at the same time are created. This happens all the time actually. We do not know why the frontend could send multiple requests at the same time. Might be some bug or in the end it could be a malicious actor.
In order to prevent this we add a unique index on `userId` and `startTime` on the booking table. It only applies to bookings in accepted state. A canceled booking might be at the same time than an accepted booking actually.
https://tourlane.atlassian.net/browse/TRIP-10537
=> [improve][TRIP-10537] Prevent duplicate bookings

apps/web/pages/booking/[uid].tsx
Show custom inputs only to authenticated users, to prevent this scenario
=> [fix] Show hidden custom inputs only to authenticated sessions

packages/core/EventManager.ts
Deleting the original booking is bad because other objects in this database are still referencing it. It also makes debugging quite frustrating.
=> [improve] Do not delete original booking when rescheduling

packages/features/bookings/lib/handleCancelBooking.ts
Add the ID of the logged in user if any to the booking metadata when a booking is cancelled. Poor man's audit logging.
=> [feat] Track user who canceled call

packages/features/bookings/lib/handleNewBooking.ts
Allow string or array as string as `user` param but without using this `getGroupName` function which is some unused Calcom feature. Now when we pass an array of string Calcom will find the first available user from the list and assign it to the booking.
=> [feat] Allow string or array of strings for user when booking

packages/trpc/server/routers/viewer/slots.tsx
When the start time is e.g. 2025-06-06T08:00:00 Calcom returns completely wrong slots for some reason. This is a quick fix and I don't even want to investigate why since we plan to get rid of Calcom anyway.
=> [fix] Fix wrong slots being returned when start time is not beginning of day

packages/features/bookings/lib/handleNewBooking.ts
Instead of throwing a generic error which results in a 500 error, respond with the appropriate HTTP status.
=> [improve] Return conflict HTTP status when no user is available
